/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arqtobd.view;

import arqtobd.model.ModelArquivoDeRegristros;

/**
 *
 * @author izaquiellbessas
 */
public class layoutArquivoRegistros extends javax.swing.JFrame {
    
    main principal;
    
    /**
     * Creates new form layoutArquivoRegistros
     * @param frameMain main
     */
    public layoutArquivoRegistros(main frameMain) {
        initComponents();
        this.jcontLinhasRegistro.setValue(1);
        this.principal = frameMain;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jlblQuantidadeLinhasRegistro = new javax.swing.JLabel();
        jlblDelimitadorCamposRegistro = new javax.swing.JLabel();
        jbtnOk = new javax.swing.JButton();
        jtxtDelimitadorCamposRegistro = new javax.swing.JTextField();
        jcontLinhasRegistro = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Layout do Arquivo de Registros");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jlblQuantidadeLinhasRegistro.setText("Quantidade de linhas por Registro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 12, 0, 0);
        getContentPane().add(jlblQuantidadeLinhasRegistro, gridBagConstraints);

        jlblDelimitadorCamposRegistro.setText("Delimitador de campos do Registro:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 12, 0, 0);
        getContentPane().add(jlblDelimitadorCamposRegistro, gridBagConstraints);

        jbtnOk.setText("OK");
        jbtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 18, 13, 12);
        getContentPane().add(jbtnOk, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 12);
        getContentPane().add(jtxtDelimitadorCamposRegistro, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 12);
        getContentPane().add(jcontLinhasRegistro, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnOkActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        int quantidadeLinhasRegistro = (int) this.jcontLinhasRegistro.getValue();
        String delimitadorCamposRegistro = this.jtxtDelimitadorCamposRegistro.getText();
        
        if (delimitadorCamposRegistro.isEmpty()) {
            delimitadorCamposRegistro = "\n";
        }
        
        principal.setModeloArquivoRegistros(new ModelArquivoDeRegristros(quantidadeLinhasRegistro, delimitadorCamposRegistro));
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnOk;
    private javax.swing.JSpinner jcontLinhasRegistro;
    private javax.swing.JLabel jlblDelimitadorCamposRegistro;
    private javax.swing.JLabel jlblQuantidadeLinhasRegistro;
    private javax.swing.JTextField jtxtDelimitadorCamposRegistro;
    // End of variables declaration//GEN-END:variables
}
