-- MySQL Script generated by MySQL Workbench
-- Sat Feb 29 14:49:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema geografia
-- -----------------------------------------------------
-- Sistema de Gerenciamento de Regiões Geográficas e/ou Geopolíticas - Base fundamental para demais sistemas que envolvem geopolítica
DROP SCHEMA IF EXISTS `geografia` ;

-- -----------------------------------------------------
-- Schema geografia
--
-- Sistema de Gerenciamento de Regiões Geográficas e/ou Geopolíticas - Base fundamental para demais sistemas que envolvem geopolítica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `geografia` ;
USE `geografia` ;

-- -----------------------------------------------------
-- Table `geografia`.`geo_Paises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geografia`.`geo_Paises` ;

CREATE TABLE IF NOT EXISTS `geografia`.`geo_Paises` (
  `nome` VARCHAR(90) NOT NULL,
  `iso_alpha2` VARCHAR(2) NOT NULL,
  `iso_alpha3` VARCHAR(3) NOT NULL,
  `iso_numero` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`iso_alpha3`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geografia`.`geo_Regioes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geografia`.`geo_Regioes` ;

CREATE TABLE IF NOT EXISTS `geografia`.`geo_Regioes` (
  `id_regiao` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_regiao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geografia`.`geo_Estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geografia`.`geo_Estados` ;

CREATE TABLE IF NOT EXISTS `geografia`.`geo_Estados` (
  `id_estado` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sigla_uf` VARCHAR(2) NOT NULL,
  `fk_pais` VARCHAR(3) NULL,
  `fk_id_regiao` INT NOT NULL,
  PRIMARY KEY (`id_estado`),
  CONSTRAINT `fk_Estados_Paises`
    FOREIGN KEY (`fk_pais`)
    REFERENCES `geografia`.`geo_Paises` (`iso_alpha3`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_geo_Estados_geo_Regioes1`
    FOREIGN KEY (`fk_id_regiao`)
    REFERENCES `geografia`.`geo_Regioes` (`id_regiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Estados_Paises1_idx` ON `geografia`.`geo_Estados` (`fk_pais` ASC) VISIBLE;

CREATE INDEX `fk_geo_Estados_geo_Regioes1_idx` ON `geografia`.`geo_Estados` (`fk_id_regiao` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `geografia`.`geo_Mesorregioes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geografia`.`geo_Mesorregioes` ;

CREATE TABLE IF NOT EXISTS `geografia`.`geo_Mesorregioes` (
  `id_mesorregiao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id_mesorregiao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geografia`.`geo_Microrregioes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geografia`.`geo_Microrregioes` ;

CREATE TABLE IF NOT EXISTS `geografia`.`geo_Microrregioes` (
  `id_micrroregiao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `fk_id_mesoregiao` INT NOT NULL,
  PRIMARY KEY (`id_micrroregiao`),
  CONSTRAINT `fk_Microregioes_Mesoregioes`
    FOREIGN KEY (`fk_id_mesoregiao`)
    REFERENCES `geografia`.`geo_Mesorregioes` (`id_mesorregiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Microregioes_Mesoregioes1_idx` ON `geografia`.`geo_Microrregioes` (`fk_id_mesoregiao` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `geografia`.`geo_Cidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geografia`.`geo_Cidades` ;

CREATE TABLE IF NOT EXISTS `geografia`.`geo_Cidades` (
  `id_cidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `geo_latitude` VARCHAR(255) NULL,
  `geo_longitude` VARCHAR(255) NULL,
  `geo_altitude` VARCHAR(255) NULL,
  `codigo_ibge` INT(9) NULL,
  `fk_id_microrregiao` INT NULL,
  `fk_id_estado` INT NOT NULL,
  PRIMARY KEY (`id_cidade`),
  CONSTRAINT `fk_Cidades_Microregioes`
    FOREIGN KEY (`fk_id_microrregiao`)
    REFERENCES `geografia`.`geo_Microrregioes` (`id_micrroregiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cidades_Estados`
    FOREIGN KEY (`fk_id_estado`)
    REFERENCES `geografia`.`geo_Estados` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cidades_Microregioes1_idx` ON `geografia`.`geo_Cidades` (`fk_id_microrregiao` ASC) VISIBLE;

CREATE INDEX `fk_Cidades_Estados1_idx` ON `geografia`.`geo_Cidades` (`fk_id_estado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `geografia`.`geo_Distritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geografia`.`geo_Distritos` ;

CREATE TABLE IF NOT EXISTS `geografia`.`geo_Distritos` (
  `id_distrito` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `geo_latitude` VARCHAR(255) NULL,
  `geo_longitude` VARCHAR(255) NULL,
  `geo_altitude` VARCHAR(255) NULL,
  `fk_id_cidade` INT NOT NULL,
  PRIMARY KEY (`id_distrito`),
  CONSTRAINT `fk_Distritos_Cidades`
    FOREIGN KEY (`fk_id_cidade`)
    REFERENCES `geografia`.`geo_Cidades` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Distritos_Cidades1_idx` ON `geografia`.`geo_Distritos` (`fk_id_cidade` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `geografia`.`geo_Sub_Distritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geografia`.`geo_Sub_Distritos` ;

CREATE TABLE IF NOT EXISTS `geografia`.`geo_Sub_Distritos` (
  `id_sub_distrito` INT NOT NULL,
  `nome` VARCHAR(120) NOT NULL,
  `geo_latitude` VARCHAR(255) NULL,
  `geo_longitude` VARCHAR(255) NULL,
  `geo_altitude` VARCHAR(255) NULL,
  `fk_id_distrito` INT NOT NULL,
  PRIMARY KEY (`id_sub_distrito`),
  CONSTRAINT `fk_geo_Sub_Distritos_geo_Distritos1`
    FOREIGN KEY (`fk_id_distrito`)
    REFERENCES `geografia`.`geo_Distritos` (`id_distrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_geo_Sub_Distritos_geo_Distritos1_idx` ON `geografia`.`geo_Sub_Distritos` (`fk_id_distrito` ASC) VISIBLE;

USE `geografia` ;

-- -----------------------------------------------------
-- Placeholder table for view `geografia`.`view_regioes_mesorregioes_microrregioes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geografia`.`view_regioes_mesorregioes_microrregioes` (`'Microrregião'` INT, `'Mesorregião'` INT, `'Região'` INT);

-- -----------------------------------------------------
-- Placeholder table for view `geografia`.`view_cidades_com_estados_e_regioes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geografia`.`view_cidades_com_estados_e_regioes` (`'Código IBGE'` INT, `'Cidades'` INT, `'Microrregião'` INT, `'Mesorregião'` INT, `'Estado/UF'` INT, `'Região'` INT);

-- -----------------------------------------------------
-- Placeholder table for view `geografia`.`view_cidades_com_todas_caracteristicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `geografia`.`view_cidades_com_todas_caracteristicas` (`'Código Sistema'` INT, `'Código IBGE'` INT, `'Cidades'` INT, `'Microrregião'` INT, `'Mesorregião'` INT, `'Estado/UF'` INT, `'Região'` INT, `'Altitude'` INT, `'Latitude'` INT, `'Longitude'` INT);

-- -----------------------------------------------------
-- View `geografia`.`view_regioes_mesorregioes_microrregioes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geografia`.`view_regioes_mesorregioes_microrregioes`;
DROP VIEW IF EXISTS `geografia`.`view_regioes_mesorregioes_microrregioes` ;
USE `geografia`;
CREATE  OR REPLACE VIEW `view_regioes_mesorregioes_microrregioes` AS
SELECT microrregioes.nome AS 'Microrregião',
	   mesorregioes.nome AS 'Mesorregião',
       regioes.nome AS 'Região'
FROM geografia.geo_regioes AS regioes,
	 geografia.geo_mesorregioes AS mesorregioes,
     geografia.geo_microrregioes AS microrregioes
WHERE mesorregioes.id_mesorregiao = microrregioes.fk_id_mesoregiao AND 
	  mesorregioes.fk_id_regiao = regioes.id_regiao
ORDER BY regioes.nome, mesorregioes.nome, microrregioes.nome
;

-- -----------------------------------------------------
-- View `geografia`.`view_cidades_com_estados_e_regioes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geografia`.`view_cidades_com_estados_e_regioes`;
DROP VIEW IF EXISTS `geografia`.`view_cidades_com_estados_e_regioes` ;
USE `geografia`;
CREATE  OR REPLACE VIEW `view_cidades_com_estados_e_regioes` AS
SELECT cidades.codigo_ibge AS 'Código IBGE',
	   cidades.nome AS 'Cidades',
	   microrregioes.nome AS 'Microrregião',
	   mesorregioes.nome AS 'Mesorregião',
       estados.sigla_uf AS 'Estado/UF',
       regioes.nome AS 'Região'
FROM geografia.geo_cidades AS cidades,
	 geografia.geo_regioes AS regioes,
	 geografia.geo_mesorregioes AS mesorregioes,
     geografia.geo_microrregioes AS microrregioes,
     geografia.geo_estados AS estados
WHERE mesorregioes.id_mesorregiao = microrregioes.fk_id_mesoregiao AND 
	  mesorregioes.fk_id_regiao = regioes.id_regiao AND
      cidades.fk_id_microrregiao = microrregioes.id_micrroregiao AND
      cidades.fk_id_estado = estados.id_estado
ORDER BY regioes.nome, estados.sigla_uf, mesorregioes.nome, microrregioes.nome, cidades.nome
;

-- -----------------------------------------------------
-- View `geografia`.`view_cidades_com_todas_caracteristicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geografia`.`view_cidades_com_todas_caracteristicas`;
DROP VIEW IF EXISTS `geografia`.`view_cidades_com_todas_caracteristicas` ;
USE `geografia`;
CREATE  OR REPLACE VIEW `view_cidades_com_todas_caracteristicas` AS
SELECT cidades.id_cidade AS 'Código Sistema',
	   cidades.codigo_ibge AS 'Código IBGE',
	   cidades.nome AS 'Cidades',
	   microrregioes.nome AS 'Microrregião',
	   mesorregioes.nome AS 'Mesorregião',
       estados.sigla_uf AS 'Estado/UF',
       regioes.nome AS 'Região',
       cidades.geo_altitude AS 'Altitude',
       cidades.geo_latitude AS 'Latitude',
       cidades.geo_longitude AS 'Longitude'
FROM geografia.geo_cidades AS cidades,
	 geografia.geo_regioes AS regioes,
	 geografia.geo_mesorregioes AS mesorregioes,
     geografia.geo_microrregioes AS microrregioes,
     geografia.geo_estados AS estados
WHERE mesorregioes.id_mesorregiao = microrregioes.fk_id_mesoregiao AND 
	  mesorregioes.fk_id_regiao = regioes.id_regiao AND
      cidades.fk_id_microrregiao = microrregioes.id_micrroregiao AND
      cidades.fk_id_estado = estados.id_estado
ORDER BY regioes.nome, estados.sigla_uf, mesorregioes.nome, microrregioes.nome, cidades.nome
;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
