-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 18:01:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sgr
-- -----------------------------------------------------
-- Sistema de Gerenciamento de Regiões - Base para demais sistemas que envolvem geopolítica
DROP SCHEMA IF EXISTS `sgr` ;

-- -----------------------------------------------------
-- Schema sgr
--
-- Sistema de Gerenciamento de Regiões - Base para demais sistemas que envolvem geopolítica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgr` ;
SHOW WARNINGS;
USE `sgr` ;

-- -----------------------------------------------------
-- Table `sgr`.`Estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgr`.`Estados` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sgr`.`Estados` (
  `idEstado` INT(11) UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  PRIMARY KEY (`idEstado`),
  UNIQUE INDEX `uqUF` (`uf` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sgr`.`Cidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sgr`.`Cidades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sgr`.`Cidades` (
  `idCidade` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `codigoIBGE` INT(11) NOT NULL,
  `fkEstado` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `fkEstado_Cidades` (`fkEstado` ASC),
  CONSTRAINT `fkEstado_Cidades__idEstado_Estados`
    FOREIGN KEY (`fkEstado`)
    REFERENCES `sgr`.`Estados` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5561
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
USE `sgr` ;

-- -----------------------------------------------------
-- Placeholder table for view `sgr`.`listar_cidades_codigoIBGE_uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgr`.`listar_cidades_codigoIBGE_uf` (`'Cidade'` INT, `'Código IBGE'` INT, `'Estado'` INT);
SHOW WARNINGS;

-- -----------------------------------------------------
-- Placeholder table for view `sgr`.`listar_cidades_uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgr`.`listar_cidades_uf` (`'Cidade'` INT, `'Estado'` INT);
SHOW WARNINGS;

-- -----------------------------------------------------
-- View `sgr`.`listar_cidades_codigoIBGE_uf`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `sgr`.`listar_cidades_codigoIBGE_uf` ;
SHOW WARNINGS;
DROP TABLE IF EXISTS `sgr`.`listar_cidades_codigoIBGE_uf`;
SHOW WARNINGS;
USE `sgr`;
CREATE  OR REPLACE VIEW `listar_cidades_codigoIBGE_uf` AS
SELECT cidades.nome AS 'Cidade', cidades.codigoIBGE AS 'Código IBGE', estados.uf AS 'Estado'
FROM sgr.cidades, sgr.estados
WHERE sgr.cidades.fkEstado = sgr.estados.idEstado;
SHOW WARNINGS;

-- -----------------------------------------------------
-- View `sgr`.`listar_cidades_uf`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `sgr`.`listar_cidades_uf` ;
SHOW WARNINGS;
DROP TABLE IF EXISTS `sgr`.`listar_cidades_uf`;
SHOW WARNINGS;
USE `sgr`;
CREATE  OR REPLACE VIEW `listar_cidades_uf` AS
SELECT cidades.nome AS 'Cidade', estados.uf AS 'Estado'
FROM sgr.cidades, sgr.estados
WHERE sgr.cidades.fkEstado = sgr.estados.idEstado;
SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
